---
- name: ship systemd service
  template:
    src: node_exporter.service.j2
    dest: "/etc/systemd/system/node_exporter.service"
    owner: root
    group: root
    mode: 0644

- name: add the cfg80211 module
  modprobe:
    name: cfg80211
    state: present

- name: open node_exporter port
  firewalld:
    port: "{{ node_exporter_port }}/tcp"
    zone: "public"
    permanent: true
    immediate: true
    state: enabled

- name: start the node_exporter service
  systemd:
    name: node_exporter
    state: started
    enabled: yes
    daemon_reload: yes
  failed_when: false