---
- name: include specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: debian based systems tasks
  include_tasks: debian_prerequisites.yml
  when:
    - ansible_os_family == 'Debian'
  tags: with_pkg

- name: install container package
  package:
    name: "{{ item }}"
    update_cache: true
  with_items:
    - '{{ container_package_name }}'
    - '{{ container_binding_name }}'
  tags: with_pkg

- name: start container service
  service:
    name: '{{ container_service_name }}'
    state: started
    enabled: yes
  tags:
    with_pkg
  when: container_service_name == 'docker'