---
galaxy_info:
  company: 45Drives
  author: Brett Kelly
  description: container installation prerequisites
  license: Apache
  min_ansible_version: 2.7
  platforms:
    - name: Ubuntu
      versions:
        - xenial
    - name: EL
      versions:
        - 7
  galaxy_tags:
    - system
dependencies: []
